services:
  app:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trajectories/root:/app/trajectories/root
    platform: linux/amd64
    environment:
      - MODEL_NAME
      - ISSUE_URL
      - BASE_COMMIT=${BASE_COMMIT:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT:-}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-https://api.openai.com/v1}
